FROM node:20.18.0 


WORKDIR /app

# install python3 and pip
RUN apt-get update && apt-get install -y python3 python3-pip
# isntall python-opencv
RUN pip install --break-system-packages opencv-python
RUN alias python=python3
# set the alias to be permanent
RUN echo "alias python=python3" >> ~/.bashrc
RUN ln -s /usr/bin/python3 /usr/bin/python

RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y

