const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

async function seed() {
    // Insira os dados manualmente
    const dataBabyInfo = [
        {
            name: "Antonia",
            birthDate: new Date("2021-04-29"), // Converte a string para Date
            isPremature: 1,
            gestationalAge: 38,
            atipicidade: "olhar descontinuo acompanhamento horizontal",
        },
        {
            name: "Davi",
            birthDate: new Date("2021-05-11"), // Converte a string para Date
            isPremature: 1,
            gestationalAge: 38,
            atipicidade:
                "olhar breve no horizontal, estrabismo convergente, tempo de fixação instável e descontinuidade do olhar no RVO",
        },
        {
            name: "Arthur",
            birthDate: new Date("2020-07-28"),
            isPremature: 1,
            gestationalAge: 39,
            atipicidade: "sem alteração",
        },
        {
            name: "Elisa",
            birthDate: new Date("2021-03-21"),
            isPremature: 1,
            gestationalAge: 40,
            atipicidade: "sem alteração",
        },
        {
            name: "Lara",
            birthDate: new Date("2020-07-01"),
            isPremature: 1,
            gestationalAge: 37,
            atipicidade: "não realiza RVO",
        },
        {
            name: "Pietra",
            birthDate: new Date("2020-11-27"),
            isPremature: 1,
            gestationalAge: 41,
            atipicidade: "sem alteração",
        },
        {
            name: "Anthony",
            birthDate: new Date("2021-05-26"), // Converte a string para Date
            isPremature: 1,
            gestationalAge: 39,
            atipicidade: "não realiza todos",
        },
        {
            name: "Ana Beatriz",
            birthDate: new Date("2021-02-22"),
            isPremature: 1,
            gestationalAge: 39,
            atipicidade: "sem alteração",
        },
        {
            name: "Giusepe",
            birthDate: new Date("2020-11-16"),
            isPremature: 1,
            gestationalAge: 32,
            atipicidade: "sem alteração",
        },
        {
            name: "Louise",
            birthDate: new Date("2020-12-22"),
            isPremature: 1,
            gestationalAge: 30,
            atipicidade:
                "acompanhamento horizontal descontínuo, estrabismo convergente, fixação instável, não realiza RVO",
        },
        {
            name: "Yohan",
            birthDate: new Date("2021-04-16"),
            isPremature: 1,
            gestationalAge: 39.0,
            atipicidade: "sem alteração",
        },
        {
            name: "Bernardo",
            birthDate: new Date("2021-10-14"),
            isPremature: 1,
            gestationalAge: 36,
            atipicidade: "acompanhamento horizontal descontínuo",
        },
        {
            name: "Luna",
            birthDate: new Date("2021-05-04"),
            isPremature: 1,
            gestationalAge: 39,
            atipicidade: "estrabismo convergente, acompanhamento horizontal breve, não realiza campo visual e RVO",
        },
        {
            name: "Rebeca",
            birthDate: new Date("2021-03-12"),
            isPremature: 1,
            gestationalAge: 26,
            atipicidade: "estrabismo convergente",
        },
        {
            name: "Bento",
            birthDate: new Date("2021-06-21"),
            isPremature: 1,
            gestationalAge: 38.0,
            atipicidade: "sem alteração",
        },
        {
            name: "Emanuel",
            birthDate: new Date("2021-03-13"),
            isPremature: 1,
            gestationalAge: 37,
            atipicidade: "sem alteração",
        },
        {
            name: "Jorge Luis",
            birthDate: new Date("2021-09-26"),
            isPremature: 1,
            gestationalAge: 28,
            atipicidade: "sem alteração",
        },
        {
            name: "Maria Cecilia",
            birthDate: new Date("2022-12-28"),
            isPremature: 1,
            gestationalAge: 29,
            atipicidade:
                "acompanhamento vertical breve, não realiza acompanhamento visual horizontal para direita e é breve, não realiza campo visual esquerdo, tempo de fixação instável, olhar descontínuo no RVO",
        },
        {
            name: "Maria Isis",
            birthDate: new Date("2022-12-28"),
            isPremature: 1,
            gestationalAge: 29,
            atipicidade:
                "não realiza acompanhamento vertical, horizontal, campo visual D, RVO, tempo de fixação instável, estrabismo convergente",
        },
        {
            name: "Otavio",
            birthDate: new Date("2019-04-16"),
            isPremature: 1,
            gestationalAge: 40,
            atipicidade: "horizontal descontínuo",
        },
        {
            name: "Theo",
            birthDate: new Date("2021-06-24"),
            isPremature: 1,
            gestationalAge: 37,
            atipicidade: "horizontal e RVO descontínuo",
        },
        {
            name: "Felipe",
            birthDate: new Date("2019-09-22"),
            isPremature: 1,
            gestationalAge: 33.0,
            atipicidade: "não tem vídeo",
        },
        {
            name: "Murialdo",
            birthDate: new Date("2022-12-28"),
            isPremature: 1,
            gestationalAge: 29,
            atipicidade: "vertical e horizontal descontínuo, fixação instável, não realiza RVO ",
        },
        {
            name: "Vinicius",
            birthDate: new Date("2021-12-01"),
            isPremature: 1,
            gestationalAge: 26,
            atipicidade: "não realiza vertical caudal, horizontal D breve e E descontínuo, RVO descontínuo",
        },
        {
            name: "Alana",
            birthDate: new Date("2022-03-27"),
            isPremature: 1,
            gestationalAge: 29.0,
            atipicidade: "choro",
        },
        {
            name: "Joao Batista",
            birthDate: new Date("2022-12-01"),
            isPremature: 1,
            gestationalAge: 38,
            atipicidade: "vertical descontínuo",
        },
        {
            name: "Arthur",
            birthDate: new Date("2021-12-23"),
            isPremature: 1,
            gestationalAge: 38,
            atipicidade: "vertical, horizontal e RVO descontínuos, fixação instável",
        },
        {
            name: "Gael",
            birthDate: new Date("2021-07-22"),
            isPremature: 1,
            gestationalAge: 40,
            atipicidade: "sem alteração",
        },
        {
            name: "Levi",
            birthDate: new Date("2022-05-23"),
            isPremature: 1,
            gestationalAge: 31,
            atipicidade: "não realiza vertical, horizontal, campo visual e RVO, fixação instável",
        },
        { name: "Iara", birthDate: new Date("1900-01-01"), isPremature: 0, gestationalAge: 0, atipicidade: "" },
        { name: "Benjamin", birthDate: new Date("2022-11-08"), isPremature: 1, gestationalAge: 39, atipicidade: "" },
        { name: "Miguel", birthDate: new Date("2021-12-10"), isPremature: 1, gestationalAge: 30, atipicidade: "" },
        { name: "Victor", birthDate: new Date("2022-07-03"), isPremature: 1, gestationalAge: 40, atipicidade: "" },
        { name: "Gabriel", birthDate: new Date("2022-10-10"), isPremature: 1, gestationalAge: 39, atipicidade: "" },
        { name: "Erick", birthDate: new Date("2022-07-31"), isPremature: 1, gestationalAge: 41, atipicidade: "" },
        { name: "Ana Sther", birthDate: new Date("2022-04-21"), isPremature: 1, gestationalAge: 33, atipicidade: "" },
        { name: "Davi", birthDate: new Date("2022-06-19"), isPremature: 1, gestationalAge: 23, atipicidade: "" },
    ];

    const dataProject = [
        {
            projectName: "camera fixa",
        },
        {
            projectName: "vestivel",
        },
    ];

    const dataProjectVideoType = [
        {
            projectId: 1,
            isMain: true,
            typeName: "Camera principal",
        },
        {
            projectId: 1,
            isMain: false,
            typeName: "Auxiliar",
        },
        {
            projectId: 2,
            isMain: true,
            typeName: "Olho Direito",
        },
        {
            projectId: 2,
            isMain: true,
            typeName: "Olho Esquerdo",
        },
        {
            projectId: 2,
            isMain: false,
            typeName: "Auxiliar",
        },
    ];

    const dataCamInfo = [
        {
            model: "HardLine Cutie 6809",
            isInfraRed: true,
            framerate: 25.74,
        },
        {
            model: "(adicionar o modelo da pequena aqui)",
            isInfraRed: true,
            projectVideoTypeId: 2,
        },
        {
            model: "(adicionar o modelo da que usam pra auxiliar a...",
            isInfraRed: false,
        },
        {
            model: "camera muito foda JKV",
            isInfraRed: true,
            framerate: 765781000000.0,
            projectVideoTypeId: 1,
        },
    ];

    const dataMovesInfo = [
        {
            description: "HorizontalSlow_Cammoving",
            projectId: 1,
        },
        {
            description: "HorizontalAbrupt_Cammoving",
            projectId: 1,
        },
        {
            description: "VerticalSlow_Cammoving",
            projectId: 1,
        },
        {
            description: "HorizontalHead_Camfixed",
            projectId: 1,
        },
    ];

    const dataRecordings = [
        { ignore: false, babyId: 8, recordingDate: new Date("2021-11-30"), moveId: 4, movAux: true, projectId: 1 },
        { ignore: false, babyId: 8, recordingDate: new Date("2021-11-30"), moveId: 1, movAux: true, projectId: 1 },
        { ignore: false, babyId: 8, recordingDate: new Date("2021-11-30"), moveId: 2, movAux: true, projectId: 1 },
        { ignore: false, babyId: 9, recordingDate: new Date("2021-11-30"), moveId: 4, movAux: true, projectId: 1 },
        {
            ignore: true,
            observation: "Video corrompido",
            babyId: 9,
            recordingDate: new Date("2021-11-30"),
            moveId: 1,
            movAux: true,
            projectId: 1,
        },
        { ignore: false, babyId: 9, recordingDate: new Date("2021-11-30"), moveId: 2, movAux: true, projectId: 1 },
        { ignore: true, babyId: 10, recordingDate: new Date("2021-11-30"), movAux: true, projectId: 1 },
        { ignore: false, babyId: 10, recordingDate: new Date("2021-11-30"), movAux: true, projectId: 1 },
        { ignore: false, babyId: 10, recordingDate: new Date("2021-11-30"), movAux: true, projectId: 1 },
        { ignore: true, babyId: 10, recordingDate: new Date("2021-11-30"), movAux: true, projectId: 1 },
        {
            ignore: false,
            observation: "Infravermelho desligado",
            babyId: 11,
            recordingDate: new Date("2021-11-30"),

            movAux: true,
            projectId: 1,
        },
        {
            ignore: false,
            observation: "Infravermelho desligado",
            babyId: 11,
            recordingDate: new Date("2021-11-30"),

            movAux: true,
            projectId: 1,
        },
        {
            ignore: false,
            observation: "Infravermelho desligado",
            babyId: 11,
            recordingDate: new Date("2021-11-30"),

            movAux: true,
            projectId: 1,
        },
        { ignore: false, babyId: 1, recordingDate: new Date("2021-12-07"), movAux: true, projectId: 1 },
        { ignore: false, babyId: 1, recordingDate: new Date("2021-12-07"), movAux: true, projectId: 1 },
        { ignore: false, babyId: 1, recordingDate: new Date("2021-12-07"), movAux: true, projectId: 1 },
        {
            ignore: true,
            observation: "Não funcionou, ficou prestando atenção na logo do computador avell, desconsiderar.",
            babyId: 2,
            recordingDate: new Date("2021-12-07"),

            movAux: true,
            projectId: 1,
        },
        {
            ignore: true,
            observation: "Não funcionou, ficou prestando atenção na logo do computador avell, desconsiderar.",
            babyId: 2,
            recordingDate: new Date("2021-12-07"),

            movAux: true,
            projectId: 1,
        },
        {
            ignore: true,
            observation: "Não funcionou, ficou prestando atenção na logo do computador avell, desconsiderar.",
            babyId: 2,
            recordingDate: new Date("2021-12-07"),

            movAux: true,
            projectId: 1,
        },
        {
            ignore: false,
            observation: "Sem Infravermelho",
            babyId: 3,
            recordingDate: new Date("2021-12-09"),

            movAux: true,
            projectId: 1,
        },
        {
            ignore: false,
            observation: "Sem Infravermelho",
            babyId: 3,
            recordingDate: new Date("2021-12-09"),

            movAux: true,
            projectId: 1,
        },
        {
            ignore: false,
            observation: "Sem Infravermelho",
            babyId: 3,
            recordingDate: new Date("2021-12-09"),

            movAux: true,
            projectId: 1,
        },
        {
            ignore: true,
            observation: "primeiro teste, bebe não deixou movimentar para o lado esquerdo dela.",
            babyId: 4,
            recordingDate: new Date("2021-12-09"),

            movAux: true,
            projectId: 1,
        },
        { ignore: false, babyId: 4, recordingDate: new Date("2021-12-09"), movAux: true, projectId: 1 },
        { ignore: false, babyId: 4, recordingDate: new Date("2021-12-09"), movAux: true, projectId: 1 },
        { ignore: false, babyId: 4, recordingDate: new Date("2021-12-09"), movAux: true, projectId: 1 },
        {
            ignore: false,
            observation: "não colaborou nos movimentos",
            babyId: 5,
            recordingDate: new Date("2021-12-09"),

            movAux: true,
            projectId: 1,
        },
        {
            ignore: false,
            observation: "não colaborou nos movimentos",
            babyId: 5,
            recordingDate: new Date("2021-12-09"),

            movAux: true,
            projectId: 1,
        },
        {
            ignore: false,
            observation: "não colaborou nos movimentos",
            babyId: 5,
            recordingDate: new Date("2021-12-09"),

            movAux: true,
            projectId: 1,
        },
        {
            ignore: false,
            observation: "não colaborou nos movimentos",
            babyId: 6,
            recordingDate: new Date("2021-12-09"),

            movAux: true,
            projectId: 1,
        },
        {
            ignore: false,
            observation: "não colaborou nos movimentos",
            babyId: 6,
            recordingDate: new Date("2021-12-09"),

            movAux: true,
            projectId: 1,
        },
        {
            ignore: false,
            observation: "não colaborou nos movimentos",
            babyId: 6,
            recordingDate: new Date("2021-12-09"),

            movAux: true,
            projectId: 1,
        },
        { ignore: true, babyId: 7, recordingDate: new Date("2021-12-14"), movAux: true, projectId: 1 },
        { ignore: false, babyId: 12, recordingDate: new Date("2022-02-22"), movAux: true, projectId: 1 },
        { ignore: false, babyId: 12, recordingDate: new Date("2022-02-22"), movAux: true, projectId: 1 },
        { ignore: false, babyId: 12, recordingDate: new Date("2022-02-22"), movAux: true, projectId: 1 },
        { ignore: false, babyId: 12, recordingDate: new Date("2022-02-22"), movAux: true, projectId: 1 },
        { ignore: false, babyId: 13, recordingDate: new Date("2022-02-22"), movAux: true, projectId: 1 },
        { ignore: false, babyId: 13, recordingDate: new Date("2022-02-22"), movAux: true, projectId: 1 },
        { ignore: false, babyId: 13, recordingDate: new Date("2022-02-22"), movAux: true, projectId: 1 },
        { ignore: false, babyId: 13, recordingDate: new Date("2022-02-22"), movAux: true, projectId: 1 },
        { ignore: false, babyId: 14, recordingDate: new Date("2022-02-22"), movAux: true, projectId: 1 },
        { ignore: false, babyId: 14, recordingDate: new Date("2022-02-22"), movAux: true, projectId: 1 },
        { ignore: false, babyId: 14, recordingDate: new Date("2022-02-22"), movAux: true, projectId: 1 },
        { ignore: false, babyId: 14, recordingDate: new Date("2022-02-22"), movAux: true, projectId: 1 },
        { ignore: false, babyId: 15, recordingDate: new Date("2022-03-22"), movAux: false, projectId: 1 },
        { ignore: false, babyId: 15, recordingDate: new Date("2022-03-22"), movAux: false, projectId: 1 },
        { ignore: false, babyId: 15, recordingDate: new Date("2022-03-22"), movAux: false, projectId: 1 },
        { ignore: false, babyId: 15, recordingDate: new Date("2022-03-22"), movAux: false, projectId: 1 },
        { ignore: false, babyId: 16, recordingDate: new Date("2022-03-22"), movAux: false, projectId: 1 },
        { ignore: false, babyId: 16, recordingDate: new Date("2022-03-22"), movAux: false, projectId: 1 },
        { ignore: false, babyId: 16, recordingDate: new Date("2022-03-22"), movAux: false, projectId: 1 },
        { ignore: false, babyId: 16, recordingDate: new Date("2022-03-22"), movAux: false, projectId: 1 },
        { ignore: false, babyId: 17, recordingDate: new Date("2022-04-05"), movAux: false, projectId: 1 },
        { ignore: false, babyId: 17, recordingDate: new Date("2022-04-05"), movAux: false, projectId: 1 },
        { ignore: false, babyId: 17, recordingDate: new Date("2022-04-05"), movAux: false, projectId: 1 },
        { ignore: false, babyId: 17, recordingDate: new Date("2022-04-05"), movAux: false, projectId: 1 },
        { ignore: false, babyId: 18, recordingDate: new Date("2022-04-05"), movAux: false, projectId: 1 },
        { ignore: false, babyId: 19, recordingDate: new Date("2022-04-05"), movAux: false, projectId: 1 },
        { ignore: false, babyId: 20, recordingDate: new Date("2022-04-05"), movAux: false, projectId: 1 },
        { ignore: false, babyId: 20, recordingDate: new Date("2022-04-05"), movAux: false, projectId: 1 },
        { ignore: false, babyId: 20, recordingDate: new Date("2022-04-05"), movAux: false, projectId: 1 },
        { ignore: false, babyId: 20, recordingDate: new Date("2022-04-05"), movAux: false, projectId: 1 },
        { ignore: true, babyId: 21, recordingDate: new Date("2022-04-05"), movAux: false, projectId: 1 },
        { ignore: false, babyId: 21, recordingDate: new Date("2022-04-05"), movAux: false, projectId: 1 },
        { ignore: false, babyId: 21, recordingDate: new Date("2022-04-05"), movAux: false, projectId: 1 },
        { ignore: false, babyId: 21, recordingDate: new Date("2022-04-05"), movAux: false, projectId: 1 },
        {
            ignore: true,
            observation: "O video não ta ali",
            babyId: 22,
            recordingDate: new Date("2022-05-31"),

            movAux: false,
            projectId: 1,
        },
        { ignore: false, babyId: 18, recordingDate: new Date("2022-05-31"), movAux: false, projectId: 1 },
        { ignore: false, babyId: 18, recordingDate: new Date("2022-05-31"), movAux: false, projectId: 1 },
        { ignore: false, babyId: 18, recordingDate: new Date("2022-05-31"), movAux: false, projectId: 1 },
        { ignore: false, babyId: 18, recordingDate: new Date("2022-05-31"), movAux: false, projectId: 1 },
        { ignore: false, babyId: 19, recordingDate: new Date("2022-05-31"), movAux: false, projectId: 1 },
        { ignore: false, babyId: 19, recordingDate: new Date("2022-05-31"), movAux: false, projectId: 1 },
        { ignore: false, babyId: 19, recordingDate: new Date("2022-05-31"), movAux: false, projectId: 1 },
        { ignore: false, babyId: 19, recordingDate: new Date("2022-05-31"), movAux: false, projectId: 1 },
        { ignore: false, babyId: 23, recordingDate: new Date("2022-05-31"), movAux: false, projectId: 1 },
        { ignore: false, babyId: 23, recordingDate: new Date("2022-05-31"), movAux: false, projectId: 1 },
        { ignore: false, babyId: 23, recordingDate: new Date("2022-05-31"), movAux: false, projectId: 1 },
        { ignore: false, babyId: 23, recordingDate: new Date("2022-05-31"), movAux: false, projectId: 1 },
        {
            ignore: false,
            observation: "Ultimo movimento de olhar falso positiv",
            babyId: 24,
            recordingDate: new Date("2022-05-31"),

            movAux: false,
            projectId: 1,
        },
        {
            ignore: false,
            observation: "Ultimo movimento de olhar falso positiv",
            babyId: 24,
            recordingDate: new Date("2022-05-31"),

            movAux: false,
            projectId: 1,
        },
        {
            ignore: false,
            observation: "Ultimo movimento de olhar falso positiv",
            babyId: 24,
            recordingDate: new Date("2022-05-31"),

            movAux: false,
            projectId: 1,
        },
        {
            ignore: false,
            observation: "Ultimo movimento de olhar falso positiv",
            babyId: 24,
            recordingDate: new Date("2022-05-31"),

            movAux: false,
            projectId: 1,
        },
        {
            ignore: false,
            observation: "Sem resposta",
            babyId: 25,
            recordingDate: new Date("2022-06-14"),

            movAux: true,
            projectId: 1,
        },
        { ignore: false, babyId: 26, recordingDate: new Date("2022-06-14"), movAux: true, projectId: 1 },
        { ignore: false, babyId: 26, recordingDate: new Date("2022-06-14"), movAux: true, projectId: 1 },
        { ignore: false, babyId: 26, recordingDate: new Date("2022-06-14"), movAux: true, projectId: 1 },
        { ignore: false, babyId: 26, recordingDate: new Date("2022-06-14"), movAux: true, projectId: 1 },
        { ignore: false, babyId: 27, recordingDate: new Date("2022-06-14"), movAux: true, projectId: 1 },
        { ignore: false, babyId: 27, recordingDate: new Date("2022-06-14"), movAux: true, projectId: 1 },
        { ignore: false, babyId: 27, recordingDate: new Date("2022-06-14"), movAux: true, projectId: 1 },
        { ignore: false, babyId: 27, recordingDate: new Date("2022-06-14"), movAux: true, projectId: 1 },
        { ignore: true, babyId: 10, recordingDate: new Date("2021-11-30"), movAux: true, projectId: 1 },
        { ignore: false, babyId: 21, recordingDate: new Date("2022-04-05"), movAux: false, projectId: 1 },
        { ignore: false, babyId: 28, recordingDate: new Date("2022-07-05"), moveId: 1, movAux: true, projectId: 1 },
        { ignore: false, babyId: 28, recordingDate: new Date("2022-07-05"), moveId: 2, movAux: true, projectId: 1 },
        { ignore: false, babyId: 28, recordingDate: new Date("2022-07-05"), moveId: 3, movAux: true, projectId: 1 },
        { ignore: false, babyId: 28, recordingDate: new Date("2022-07-05"), moveId: 4, movAux: true, projectId: 1 },
        {
            ignore: true,
            observation: "Nao fixa",
            babyId: 29,
            recordingDate: new Date("2022-07-05"),
            moveId: 1,
            movAux: true,
            projectId: 1,
        },
        {
            ignore: true,
            observation: "Muito agitada",
            babyId: 14,
            recordingDate: new Date("2022-07-05"),
            moveId: 1,
            movAux: true,
            projectId: 1,
        },
        {
            ignore: true,
            observation: "Muito agitada",
            babyId: 14,
            recordingDate: new Date("2022-07-05"),
            moveId: 2,
            movAux: true,
            projectId: 1,
        },
        {
            ignore: true,
            observation: "Muito agitada",
            babyId: 14,
            recordingDate: new Date("2022-07-05"),
            moveId: 3,
            movAux: true,
            projectId: 1,
        },
        {
            ignore: true,
            observation: "Muito agitada",
            babyId: 14,
            recordingDate: new Date("2022-07-05"),
            moveId: 4,
            movAux: true,
            projectId: 1,
        },
        {
            ignore: true,
            observation: "sem sucesso",
            babyId: 21,
            recordingDate: new Date("2022-07-05"),
            moveId: 4,
            movAux: true,
            projectId: 1,
        },
        {
            ignore: true,
            observation: "sem sucesso",
            babyId: 21,
            recordingDate: new Date("2022-07-05"),
            moveId: 4,
            movAux: true,
            projectId: 1,
        },
        {
            ignore: true,
            observation: "falha, crianca nao executou",
            babyId: 9,
            recordingDate: new Date("2022-07-15"),
            moveId: 1,
            movAux: true,
            projectId: 1,
        },
        {
            ignore: true,
            observation: "Falha, ambiente ruidoso",
            babyId: 30,
            recordingDate: new Date("2022-07-26"),
            moveId: 1,
            movAux: true,
            projectId: 1,
        },
        { ignore: false, babyId: 18, recordingDate: new Date("2022-07-26"), moveId: 1, movAux: true, projectId: 1 },
        { ignore: false, babyId: 18, recordingDate: new Date("2022-07-26"), moveId: 2, movAux: true, projectId: 1 },
        { ignore: false, babyId: 18, recordingDate: new Date("2022-07-26"), moveId: 3, movAux: true, projectId: 1 },
        { ignore: false, babyId: 18, recordingDate: new Date("2022-07-26"), moveId: 4, movAux: true, projectId: 1 },
        { ignore: false, babyId: 19, recordingDate: new Date("2022-07-26"), moveId: 1, movAux: true, projectId: 1 },
        { ignore: false, babyId: 19, recordingDate: new Date("2022-07-26"), moveId: 2, movAux: true, projectId: 1 },
        { ignore: false, babyId: 19, recordingDate: new Date("2022-07-26"), moveId: 3, movAux: true, projectId: 1 },
        { ignore: false, babyId: 19, recordingDate: new Date("2022-07-26"), moveId: 4, movAux: true, projectId: 1 },
        { ignore: false, babyId: 23, recordingDate: new Date("2022-07-26"), moveId: 1, movAux: true, projectId: 1 },
        { ignore: false, babyId: 23, recordingDate: new Date("2022-07-26"), moveId: 2, movAux: true, projectId: 1 },
        { ignore: false, babyId: 23, recordingDate: new Date("2022-07-26"), moveId: 3, movAux: true, projectId: 1 },
        { ignore: false, babyId: 23, recordingDate: new Date("2022-07-26"), moveId: 4, movAux: true, projectId: 1 },
        { ignore: false, babyId: 17, recordingDate: new Date("2022-07-26"), moveId: 1, movAux: true, projectId: 1 },
        { ignore: false, babyId: 17, recordingDate: new Date("2022-07-26"), moveId: 2, movAux: true, projectId: 1 },
        { ignore: false, babyId: 17, recordingDate: new Date("2022-07-26"), moveId: 3, movAux: true, projectId: 1 },
        { ignore: false, babyId: 17, recordingDate: new Date("2022-07-26"), moveId: 4, movAux: true, projectId: 1 },
        {
            ignore: false,
            observation: "movimento 1 ok",
            babyId: 31,
            recordingDate: new Date("2022-12-08"),
            moveId: 1,
            movAux: true,
            projectId: 1,
        },
        {
            ignore: true,
            observation: "movimento 2 nao",
            babyId: 31,
            recordingDate: new Date("2022-12-08"),
            moveId: 2,
            movAux: true,
            projectId: 1,
        },
        {
            ignore: false,
            observation: "movimento 3 e 4 - mesmo video. COnfirmou movimento 3.",
            babyId: 31,
            recordingDate: new Date("2022-12-08"),
            moveId: 3,
            movAux: true,
            projectId: 1,
        },
        {
            ignore: true,
            observation: "movimento 3 e 4 - mesmo video. COnfirmou movimento 3.",
            babyId: 31,
            recordingDate: new Date("2022-12-08"),
            moveId: 4,
            movAux: true,
            projectId: 1,
        },
        {
            ignore: true,
            observation: "sem resposta",
            babyId: 28,
            recordingDate: new Date("2022-12-08"),
            moveId: 1,
            movAux: true,
            projectId: 1,
        },
        {
            ignore: true,
            observation: "sem resposta",
            babyId: 28,
            recordingDate: new Date("2022-12-08"),
            moveId: 2,
            movAux: true,
            projectId: 1,
        },
        {
            ignore: true,
            observation: "sem resposta",
            babyId: 28,
            recordingDate: new Date("2022-12-08"),
            moveId: 3,
            movAux: true,
            projectId: 1,
        },
        {
            ignore: true,
            observation: "sem resposta",
            babyId: 28,
            recordingDate: new Date("2022-12-08"),
            moveId: 4,
            movAux: true,
            projectId: 1,
        },
        { ignore: false, babyId: 27, recordingDate: new Date("2022-09-01"), moveId: 1, movAux: true, projectId: 1 },
        { ignore: false, babyId: 27, recordingDate: new Date("2022-09-01"), moveId: 2, movAux: true, projectId: 1 },
        { ignore: false, babyId: 27, recordingDate: new Date("2022-09-01"), moveId: 3, movAux: true, projectId: 1 },
        { ignore: false, babyId: 27, recordingDate: new Date("2022-09-01"), moveId: 4, movAux: true, projectId: 1 },
        { ignore: false, babyId: 32, recordingDate: new Date("2022-09-01"), moveId: 1, movAux: true, projectId: 1 },
        { ignore: false, babyId: 32, recordingDate: new Date("2022-09-01"), moveId: 2, movAux: true, projectId: 1 },
        { ignore: false, babyId: 32, recordingDate: new Date("2022-09-01"), moveId: 3, movAux: true, projectId: 1 },
        { ignore: false, babyId: 32, recordingDate: new Date("2022-09-01"), moveId: 4, movAux: true, projectId: 1 },
        {
            ignore: true,
            observation: "Nao fixou",
            babyId: 33,
            recordingDate: new Date("2022-09-01"),
            moveId: 1,
            movAux: true,
            projectId: 1,
        },
        {
            ignore: true,
            observation: "Nao fixou",
            babyId: 33,
            recordingDate: new Date("2022-09-01"),
            moveId: 2,
            movAux: true,
            projectId: 1,
        },
        {
            ignore: true,
            observation: "sem resposta, nao executado os seguintes",
            babyId: 34,
            recordingDate: new Date("2022-12-09"),
            moveId: 1,
            movAux: true,
            projectId: 1,
        },
        {
            ignore: true,
            observation: "sem resposta, nao executado os seguintes",
            babyId: 34,
            recordingDate: new Date("2022-12-09"),
            moveId: 2,
            movAux: true,
            projectId: 1,
        },
        {
            ignore: false,
            observation: "Muito disperso",
            babyId: 15,
            recordingDate: new Date("2022-09-16"),
            moveId: 1,
            movAux: true,
            projectId: 1,
        },
        {
            ignore: false,
            observation: "Muito disperso",
            babyId: 15,
            recordingDate: new Date("2022-09-16"),
            moveId: 2,
            movAux: true,
            projectId: 1,
        },
        {
            ignore: true,
            observation: "3 falhou, 4 nao feito",
            babyId: 15,
            recordingDate: new Date("2022-09-16"),
            moveId: 3,
            movAux: true,
            projectId: 1,
        },
        { ignore: false, babyId: 3, recordingDate: new Date("2022-09-30"), moveId: 1, movAux: true, projectId: 1 },
        { ignore: false, babyId: 3, recordingDate: new Date("2022-09-30"), moveId: 2, movAux: true, projectId: 1 },
        { ignore: false, babyId: 3, recordingDate: new Date("2022-09-30"), moveId: 3, movAux: true, projectId: 1 },
        { ignore: false, babyId: 3, recordingDate: new Date("2022-09-30"), moveId: 4, movAux: true, projectId: 1 },
        {
            ignore: true,
            observation: "Falhou",
            babyId: 4,
            recordingDate: new Date("2022-09-30"),
            moveId: 1,
            movAux: true,
            projectId: 1,
        },
        { ignore: false, babyId: 13, recordingDate: new Date("2022-09-30"), moveId: 1, movAux: true, projectId: 1 },
        { ignore: false, babyId: 13, recordingDate: new Date("2022-09-30"), moveId: 2, movAux: true, projectId: 1 },
        { ignore: false, babyId: 13, recordingDate: new Date("2022-09-30"), moveId: 3, movAux: true, projectId: 1 },
        { ignore: false, babyId: 13, recordingDate: new Date("2022-09-30"), moveId: 4, movAux: true, projectId: 1 },
        { ignore: false, babyId: 35, recordingDate: new Date("2022-10-14"), moveId: 1, movAux: true, projectId: 1 },
        { ignore: false, babyId: 35, recordingDate: new Date("2022-10-14"), moveId: 2, movAux: true, projectId: 1 },
        { ignore: false, babyId: 35, recordingDate: new Date("2022-10-14"), moveId: 3, movAux: true, projectId: 1 },
        {
            ignore: false,
            observation: "ultimo movimento durou poucoo tempo, invalido",
            babyId: 35,
            recordingDate: new Date("2022-10-14"),
            moveId: 4,
            movAux: true,
            projectId: 1,
        },
        {
            ignore: false,
            observation: "Lado direito nao fixando ?",
            babyId: 36,
            recordingDate: new Date("2022-10-14"),
            moveId: 1,
            movAux: true,
            projectId: 1,
        },
        {
            ignore: false,
            observation: "Lado direito nao fixando ?",
            babyId: 36,
            recordingDate: new Date("2022-10-14"),
            moveId: 2,
            movAux: true,
            projectId: 1,
        },
        {
            ignore: false,
            observation: "Lado direito nao fixando ?",
            babyId: 36,
            recordingDate: new Date("2022-10-14"),
            moveId: 3,
            movAux: true,
            projectId: 1,
        },
        {
            ignore: false,
            observation: "Lado direito nao fixando ?",
            babyId: 36,
            recordingDate: new Date("2022-10-14"),
            moveId: 4,
            movAux: true,
            projectId: 1,
        },
        {
            ignore: true,
            observation: "nao fixou em nenhum movimento, 4 nao realizado",
            babyId: 37,
            recordingDate: new Date("2022-11-04"),
            moveId: 1,
            movAux: true,
            projectId: 1,
        },
        {
            ignore: true,
            observation: "nao fixou em nenhum movimento, 4 nao realizado",
            babyId: 37,
            recordingDate: new Date("2022-11-04"),
            moveId: 2,
            movAux: true,
            projectId: 1,
        },
        {
            ignore: true,
            observation: "nao fixou em nenhum movimento, 4 nao realizado",
            babyId: 37,
            recordingDate: new Date("2022-11-04"),
            moveId: 3,
            movAux: true,
            projectId: 1,
        },
        { ignore: false, babyId: 18, recordingDate: new Date("2022-11-04"), moveId: 1, movAux: true, projectId: 1 },
        { ignore: false, babyId: 18, recordingDate: new Date("2022-11-04"), moveId: 2, movAux: true, projectId: 1 },
        { ignore: false, babyId: 18, recordingDate: new Date("2022-11-04"), moveId: 3, movAux: true, projectId: 1 },
        { ignore: false, babyId: 18, recordingDate: new Date("2022-11-04"), moveId: 4, movAux: true, projectId: 1 },
        { ignore: false, babyId: 19, recordingDate: new Date("2022-11-04"), moveId: 1, movAux: true, projectId: 1 },
        { ignore: false, babyId: 19, recordingDate: new Date("2022-11-04"), moveId: 2, movAux: true, projectId: 1 },
        { ignore: false, babyId: 19, recordingDate: new Date("2022-11-04"), moveId: 3, movAux: true, projectId: 1 },
        { ignore: false, babyId: 19, recordingDate: new Date("2022-11-04"), moveId: 4, movAux: true, projectId: 1 },
        { ignore: false, babyId: 23, recordingDate: new Date("2022-11-04"), moveId: 1, movAux: true, projectId: 1 },
        { ignore: false, babyId: 23, recordingDate: new Date("2022-11-04"), moveId: 2, movAux: true, projectId: 1 },
        { ignore: false, babyId: 23, recordingDate: new Date("2022-11-04"), moveId: 3, movAux: true, projectId: 1 },
        { ignore: false, babyId: 23, recordingDate: new Date("2022-11-04"), moveId: 4, movAux: true, projectId: 1 },
    ];

    const dataRecordVideoTypeCamUsed = [
        {
            camIdUsed: 4,
            recordingId: 34,
            projectVideoTypeId: 1,
        },
    ];

    try {
        // Manipulação de dataBabyInfo para tratar o campo `isPremature`
        const updatedBabyInfo = dataBabyInfo.map((baby) => ({
            ...baby,
            isPremature: baby.isPremature === 1, // Transforma 1 em true e 0 em false
        }));
        await prisma.$transaction([
            // Manipulação específica de `babyInfo` para tratar o campo `isPremature`
            prisma.babyInfo.createMany({
                data: updatedBabyInfo,
            }),
            prisma.project.createMany({
                data: dataProject,
            }),
            prisma.projectVideoType.createMany({
                data: dataProjectVideoType,
            }),
            prisma.camInfo.createMany({
                data: dataCamInfo,
            }),
            prisma.movesInfo.createMany({
                data: dataMovesInfo,
            }),
            prisma.recording.createMany({
                data: dataRecordings,
            }),
            prisma.recordVideoTypeCamUsed.createMany({
                data: dataRecordVideoTypeCamUsed,
            }),
        ]);
    } catch (error) {
        console.error("Error inserting data:", error);
    }
}

seed()
    .then(async () => {
        await prisma.$disconnect();
    })
    .catch(async (e) => {
        console.error(e);
        await prisma.$disconnect();
        process.exit(1);
    });
